# Quick compose config for testing local dev code
# 27/03/22
#
# - Build with `docker-compose -f docker-compose.local.yml build`
# - Uses Dockerfile-noinstall, which pulls requirements but DOESN'T install ePSproc or PEMtk.
# - Mount local dir, e.g. /mnt/d/code/github, for local source code access.
# - Mount local dir, e.g. /mnt/d/temp/docker_stimpy_builds/notebooks, for local files.
#
# Modified for Syno env + some local settings + ePS version of lab
# 10/08/21
# Original: https://github.com/defeo/jupyterhub-docker
# For more options, see https://docs.docker.com/compose/reference/
# For base Jupyter Docker stacks info, see https://jupyter-docker-stacks.readthedocs.io/en/latest/using/running.html

version: '3.7'

services:

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile-noinstall-latest

    image: jupyterlab_epsproc_dev
    container_name: jupyterlab-ePSproc-dev
    # network_mode: none
    # command: echo
    ports:
      - 8966:8888
    volumes:
      # Option (1): set Docker-managed volume for user data (no additional config required)
      - jupyter_data:/home/jovyan/work
      # Option (2): mount local paths
      # - <local path to notebooks>:/home/jovyan/work
      # - <local path for .jupyter>:/home/jovyan/.jupyter  # Set .jupyter to add a persistent settings dir over builds.

# Set persistent volume with default Docker settings.
volumes:
  jupyter_data:


# For network sharing issue, e.g. OVPN, set network directly here - see https://stackoverflow.com/a/56136591
# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.21.0.1/24
